name: Create Release and Publish NuGet
run-name: ${{ github.actor }} is creating a new NuGet package
on:
  push:
    branches:
      - master
jobs:
  Publish-Package-To-NuGet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."

  Run-Tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.4.2

      - run: echo "${{ env.NuGetDirectory }} or ${{ github.workspace}}/nuget"

      - name: Run Unit Tests
        run: dotnet test -c Release .\Yonii.Utils.UnitTests\Yonii.Utils.UnitTests.csproj

  Create-NuGet:
    needs: [Run-Tests]
    name: Create NuGet Package
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Checkout the git repository
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.4.2

      # Build project
      - name: Build
        run: dotnet build -c Release

      - name: Pack nuget
        run: dotnet pack -c Release --no-build --output
    

  
